apiVersion: v1
kind: Service
metadata:
  name: hostinfo-service
  labels:
    app: hostinfo-app
spec:
  selector:
    app: hostinfo-app
  type: NodePort
  ports:
  - nodePort: 31000
    port: 9000
    targetPort: 9000